<img src = "https://github.com/barcelonagse-datascience/academic_files/raw/master/bgsedsc_0.jpg">

## Extra challenges for Python (+Numpy and Pandas)

This is a short list of short challenges to practice

### Lists

In [ ]:
# Challenge 1: Create a list variable with a sequence of numbers from 1 to 10.

In [ ]:
# Challenge 2: From previous one,  set the 2nd and 6th elements to 'no value'

In [ ]:
# Challenge 3: From previous one,  print last 3 elements of the list

In [ ]:
# Challenge 4: From #3, sum all the elements that are not None
# Hint: do it first with a for loop, then try the same with a list comprehension

## Tuples

In [ ]:
# Challenge 1: Create a list of 6 tuples, each tuple would be a pair of name and an age (to your choice, but one has to be 'bob')

array([[ -4, -52],
       [  4,   0]])

In [ ]:
# Challenge 2: Print bob's age

In [ ]:
# Challenge 3: Extract names of people whose age is under certain value

## Dictionaries

In [ ]:
# Challenge 1: Create a list of dictionaries using same info that we had in the list of tuple of challenge #1 in tuples

In [ ]:
# Challenge 2: Print bob's age

In [ ]:
# Challenge 3: Extract names of people whose age is under certain value
# Do it first using for a loop, then a list comprehension

In [ ]:
# Challenge 4: Add a new key to our list of dictionaries, that is the ages of best friends of the related person

## Functions

In [ ]:
# Challenge 1: Build a function that receives as input one tuple from our list of tuples (tuples section) , and returns the name and (his age + 10)
 
# Test it with this function
onetuple=#one of the valid tuples
check_age(onetuple)

In [ ]:
# Challenge 2: Apply previous function to all tuples in our list of tuples

In [ ]:
# Challenge 3: Build a function that receives as input one name the dictionary that we built in challenge #3 (section dictionaries) and yields a tuple of 'name' and maximum age of best friends
# Test it with some names of our list of dictionaries

In [ ]:
# Challenge 4: Modify previus function, so that handles names that are not present
# i.e. when checking a new names, yield a message such as ('Robert is not in our list')

# Test it with a new name

In [ ]:
# Challenge 5: Aply previous function to all names in our list of dictionaries

## Numpy arrays

In [ ]:
# Challenge 1: Create two vectors (arrays) whose content is (2,5,7) and (3,5,7)
# don't forget to import numpy module

In [ ]:
# Challenge 2: Compute the dot product of the previous vectors

In [ ]:
# Challenge 3: Concatenate both vectors (arrays) into one

In [ ]:
# Challenge 3: Get previous vector and reshape to a matrix (2d array) of 2 rows and 3 columns

In [ ]:
# CHallenge 4: Create a similar matrix with values (3,6,3,1,1,0) and sum with previous matrix

In [ ]:
# Challenge 5: From previous step, instead of sum, concatenate bot matrices, so that you end up having a 4x3 matrix (2d array)

In [ ]:
# Challenge 6: Extract elments #2 and #3 of rows #1 and#4 of previous matrix

In [ ]:
# Challenge 7: Extract average value by rows of our matrix, and also mean value by columns

# Pandas series

In [ ]:
# Challenge 1: From our list of tuples created in #1 (tuples section), create a pandas series that has as index the names, and as values the ages
# don't forget to import pandas

In [ ]:
# Challenge 2: Set as empty value the second element of the series

In [ ]:
# Challenge 3: Change bob's age to 52

In [ ]:
# Challenge 4: Save the list of names acting as index, then reset index of the series

In [ ]:
# Challenge 5: Sort the series, print it to spot the maximum, and print the maximum age first using .iloc, then using index

In [ ]:
# Challenge 6: Build a mask and remove empty values

In [ ]:
# Challenge 7: Report names of people between 18 and 30 years

In [ ]:
# Challenge 8: Build a function that raises a number to a power of two, and apply it to our series using .map